groups:
  - name: Master
    jobs:
      - job-unit-test-master
      - job-dh-push-master
      - job-ecs-deploy-master

resources:
  - name: hw-master
    type: git
    source:
      uri: ((github_url))
      username: ((username))
      password: ((password))
      branch: master
  - name: dh-repo-master
    type: docker-image
    source: &dh-repo
      uri: "https://cloud.docker.com/repository/docker/grodda/hello-world-cicd"
      username: "grodda"
      password: "Jenny@123"
      repository: "grodda/hello-world-cicd"

jobs:
  - name: job-unit-test-master
    public: true
    serial: true
    plan:
      - get: hello-world-cicd
        resource: hw-master
        trigger: true
      - task: unit-test-master
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: node}
          inputs:
            - name: hello-world-cicd
              path: hello-world-cicd
          run:
            path: sh
            args:
              - -c
              - |
                cd hello-world-cicd/
                npm install
                npm test
  - name: job-dh-push-master
    public: true
    plan:
      - get: hello-world-cicd
        resource: hw-master
        version: "every"
        trigger: true
        passed: [job-unit-test-master]
      - put: dh-repo-master
        params:
          build: hello-world-cicd
          dockerfile: hello-world-cicd/Dockerfile
  - name: job-ecs-deploy-master
    public: true
    plan:
      - get: hello-world-cicd
        resource: hw-master
        version: "every"
        trigger: true
        passed: [job-dh-push-master]
      - task: ecs-deploy-master
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: { repository: sahsu/docker-ecs-cli}

          inputs:
            - name: hello-world-cicd
              path: hello-world-cicd
          run:
            path: sh
            args:
              - -c
              - |
                ls -al
                chmod 755 ./hello-world-cicd/ci/master/ecs-cli-deploy.sh
                ./hello-world-cicd/ci/master/ecs-cli-deploy.sh ((aws_access_key_id)) ((aws_secret_access_key))

